### PR TITLE
Add compatibility with INDI 2.0 and cleanup

### PR DESCRIPTION
**Pull request by paolostivanin**
* update the bundled INDI code from 1.7.4 to 1.8.7 (newest versions require more work, so I'll open a separate PR for that)
* update phdindiclient.h as per https://github.com/indilib/indi/issues/1833 (thanks @pawel-soja). This is a workaround for INDI 2.0 compatibility until PHD2 code is fully migrated to the new syntax.
* cleanup ifses for ancient INDI versions (<=1.4)

I've compiled and executed PHD2 for both the bundled INDI (1.8.7) and the system INDI (2.0.0) on openSUSE Tumbleweed. It would be nice if we could get more feedback from other users though :smile:

### CODE REVIEW

**Review by agalasso — COMMENTED** [review]
Thanks for the PR!   I will test this with Windows and Mac. If I do not see any issues with those platforms we can merge this.

**Comment by paolostivanin** [comment]
Cool, thank you Andrea!

**Review by agalasso — APPROVED** [review]
no build issues for Windows or Mac, so we're all set to merge this

**Comment by jpaana** [comment]
With current GIT version of INDI, PHD2 now compiles, but says connecting to mount times out even though PHD2 correctly finds the devices and shows properties correctly. Using bundled INDI works correctly.

**Comment by paolostivanin** [comment]
What INDI version is installed on your system? And what OS are you using?

**Comment by jpaana** [comment]
I don't use system packages for these, INDI, 3rd-party drivers, KStars, PHD2 and so on are all compiled from GIT. I update all repos first and rebuild everything in order (INDI -> 3rd-party -> KStars -> PHD2), so everything was updated at the same time yesterday. OS is Ubuntu 22.04 LTS on x64 machine. The time outing mount in question is EQMod if that makes a difference. KStars had already connected all the devices and PHD2 saw everything fine, but connecting to mount and aux mount time out. My guide camera is Lodestar X2 which I use directly via PHD2 and not INDI.

**Comment by pchev** [comment]
Can you look at the PHD2 debug log if there is any message about why it timeout the mount?

**Comment by paolostivanin** [comment]
@pawel-soja do you think [this](https://github.com/indilib/indi/issues/1833#issuecomment-1413666772) could be causing the issue? Or could it be something else?

**Comment by paolostivanin** [comment]
@jpaana could you please open an issue for this? thanks!

**Comment by pawel-soja** [comment]
I am not an active PHD2 user, yet (I use Ekos). I have no information whether the project worked, for example, for version 1.9.9 and it's hard for me to determine whether the recent changes have had a negative impact on the project.

I will be happy to help and support PHD2. And so I'm going to check what this project can do. I will try to check soon where is the problem.

Has anyone been able to reproduce the problem?

**Comment by paolostivanin** [comment]
Can confirm that also my cem70 doesn't connect if I use INDI 2.0. I'll open a PR to revert part of this PR and force INDI to be < 2.0 if using system INDI.

**Comment by paolostivanin** [comment]
PHD2 now throws an error at compile time if INDI 2.0 is being detected: https://github.com/OpenPHDGuiding/phd2/pull/1035

**Comment by jpaana** [comment]
Opened an issue with debug log attached. Unfortunately it didn't show anything obviously wrong to me.

**Comment by pawel-soja** [comment]
See https://github.com/OpenPHDGuiding/phd2/issues/1036

**Pull request merged**
