### PR TITLE
[WIP] Update QHY SDK to 20.08.26_3 for all platforms

### PR DESCRIPTION
**Pull request by daleghent**
[WORK IN PROGRESS]

This PR:
* Updates the QHY SDK to the 20.08.26_3 version for all platforms
* Moves the QHY header files to their own subdirectory, `cameras/qhyccd/`
* Updates the `unpack_qhy_sdk.sh` script for the current SDK archive layouts
* The macOS `libqhyccd.dylib` is now a Mach-O multi-arch object that contains both x86 and x64 objects, so there is no-longer a need for separate per-arch shared objects.

@agalasso I'm running with the git config `autocrlf = true` in my Windows/MNGW git environment. Is this ok in terms of line ending conventions for the project? I ask because a lot of the header file diff content is due to different line endings compared to what the existing files in the repo already had.

I'll need some double-checking on macOS and Linux.

### CODE REVIEW

**Comment by agalasso** [comment]
> I'm running with the git config `autocrlf = true` in my Windows/MNGW git environment. Is this ok in terms of line ending conventions for the project? I ask because a lot of the header file diff content is due to different line endings compared to what the existing files in the repo already had.

@daleghent I have been leaving the line endings untouched per file to not introduce big whitespace diffs.   Ideally it would be best to make a separate PR to change line endings (only) as that will give the cleanest git history.

**Comment by agalasso** [comment]
> I'll need some double-checking on macOS and Linux.

@daleghent should I go ahead and test this now on mac & Linux?

**Comment by daleghent** [comment]
> 
> 
> > I'll need some double-checking on macOS and Linux.
> 
> @daleghent should I go ahead and test this now on mac & Linux?

Yes, please do!

**Comment by agalasso** [comment]
@daleghent I was looking at this today. We need a couple tweaks for the Mac builds to deal with the dylib -- locating it at build time (trivial change) and packaging and locating it at runtime.
I am working on those changes and will send you a PR to this branch.

**Comment by agalasso** [comment]
I'm seeing an intermittent crash with 64-bit Mac with the new SDK with my QHY5L-II-C. I was not able to reproduce the crash on 32-bit Mac, but I did not try very hard. AFAICT does not repro on Windows (I tried a little harder to repro it but could not repro.)

Steps to reproduce:
 - connect camera
 - enable subframes
 - loop exposures, 1s duration
 - click on a hot pixel to switch to sub-frames
 - crashes (see crash report attached)
 - if no crash, Shift-click to de-select the hot pixel and return to full frames, repeat click on hot pixel

[crash.txt](https://github.com/OpenPHDGuiding/phd2/files/5323949/crash.txt)

**Comment by daleghent** [comment]
> I'm seeing an intermittent crash with 64-bit Mac with the new SDK with my QHY5L-II-C. I was not able to reproduce the crash on 32-bit Mac, but I did not try very hard. AFAICT does not repro on Windows (I tried a little harder to repro it but could not repro.)
> 
> Steps to reproduce:
> 
> * connect camera
> * enable subframes
> * loop exposures, 1s duration
> * click on a hot pixel to switch to sub-frames
> * crashes (see crash report attached)
> * if no crash, Shift-click to de-select the hot pixel and return to full frames, repeat click on hot pixel
> 
> [crash.txt](https://github.com/OpenPHDGuiding/phd2/files/5323949/crash.txt)

Hmm, it looks like this is crashing with an exception in `libusb_openphd.dylib:: darwin_cancel_transfer()` after the driver calls `CancelQHYCCDExposingAndReadout()` in the SDK: 

```
Thread 3 Crashed:
0   libusb_openphd.dylib          	0x000000010e395c52 darwin_cancel_transfer + 450
1   libusb_openphd.dylib          	0x000000010e38e102 libusb_cancel_transfer + 98
2   libqhyccd.dylib               	0x000000010e85ce41 StopAsyQCamLive(void*) + 273
3   libqhyccd.dylib               	0x000000010e8d25e9 QHY5IIBASE::CancelExposing(void*) + 57
4   libqhyccd.dylib               	0x000000010e8d2692 QHY5IIBASE::CancelExposingAndReadout(void*) + 82
5   libqhyccd.dylib               	0x000000010e8662fe CancelQHYCCDExposingAndReadout + 142
6   PHD2                          	0x000000010d4e1132 Camera_QHY::Capture(int, usImage&, int, wxRect const&) + 802
7   PHD2                          	0x000000010d728a0d WorkerThread::HandleExpose(EXPOSE_REQUEST*) + 285
8   PHD2                          	0x000000010d72a6d8 WorkerThread::Entry() + 1048
9   PHD2                          	0x000000010dc3845c wxThread::CallEntry() + 12
10  PHD2                          	0x000000010dc37ec9 wxThreadInternal::PthreadStart(wxThread*) + 2185
11  libsystem_pthread.dylib       	0x00007fff7246b109 _pthread_start + 148
12  libsystem_pthread.dylib       	0x00007fff72466b8b thread_start + 15
```

We don't seem to ship anything called `libusb_openphd.dylib` yet that object name seems awfully specific. I wonder if this is baked into the macOS SDK.

**Comment by agalasso** [comment]
> We don't seem to ship anything called `libusb_openphd.dylib`

We build libusb from source into libusb_openphd.dylib and package it with the macos PHD2 bundle via thirdparty/thirdparty.cmake.
I highly doubt the problem is with libusb, much more likely in the callers (StopAsyQCamLive/QHY5IIBASE::CancelExposing/...) but the calling code is in the closed source QHY SDK so I believe our best option is to get QHY to diagnose it.

**Comment by daleghent** [comment]
I contacted QHY about the Mac issue earlier this past week, but it was a national holiday in China. I've received some followup questions from them now and will work with them on hunting down this issue

**Comment by daleghent** [comment]
I am beginning to wonder if the libusb we ship is too stale for contemporary macOS versions and if updating it from 1.0.21 to 10.0.23 (the current release) might improve behavior on macOS. Reference the libusb project change log:

https://github.com/libusb/libusb/blob/master/ChangeLog

I will see about getting a PHD2 build environment set up on my mac and verify whether my QHY5-III-462C encounters the same problem, and if a newer libusb brings any favorable results

**Comment by daleghent** [comment]
Picking this back up. 

- Updated Windows SDK to 21.2.19.19 to support new cameras and newer Cypress Semiconductor FX3 IO libraries.

**Comment by daleghent** [comment]
I've worked out a build environment on macOS 11.2 (Big Sur). There are some changes that will need to be made to `run_cmake-osx` to support the architectural changes that came with Big Sur. Mainly it has to do with the fact the the vast majority of `/usr/lib` on macOS has been cleared out, with the dynamic libraries now residing in the osx dynlib cache. This means that the system libraries we lean on (libcurl, libz) are accessible only via `dlopen()` and friends. They are no longer actual files that you can see/stat in `/usr/lib`. This means the existing thirdparty cmake rules fail. I've found the way out of this predicament, but I will need help testing this on older macOS releases as all my stuff is on Big Sur.

**Comment by agalasso** [comment]
> I will need help testing this on older macOS releases as all my stuff is on Big Sur.

@daleghent  Thanks for continuing to work on this.  Whenever you are ready just let me know and I will test your changes on my old 32-bit mac (10.7 Lion) and newer 10.15 Catalina.
I won't be able to get to it any earlier than this weekend though.

**Pull request closed without merging**
